### ISSUE TITLE
gl-window initargs for width/height do not allow floats

### ISSUE THREAD

**Issue by mfiano** [lispgames/sdl2kit#1]
I would like to specify my width/height as single-float's so that i can use them without casting them as floats in the various places that require float width/height, such as creating a vec4 with mathkit to represent a viewport. Currently gl-window fails to initialize due to not being type unsigned-byte 32.

**Comment by rpav** [comment]
Note you can of course truncate your floats passing them to things requiring integers.  This can easily take general numbers, though.  Pushed as 79d3e3382e5dda60544704b918665fa4a467b77c.
