### ISSUE TITLE
2 possible minor problems

### ISSUE THREAD

**Issue by mfiano** [lispgames/sdl2kit#4]
2 things I just noticed, but may or may not be 'bugs' and just my lack of understanding.

1) If I call a function that calls READ inside of sdl2:in-main-thread, it cannot eval forms read, as it's trying to eval in the CL-USER package. This same function works as expected before or after the sdl2:in-main-thread form. Is this normal, or should sdl2:in-main-thread create a thread in the current package?

2) This is very minor. I use keyboard-event to print to stdout which key was pressed upon input. If I call close-window upon pressing Escape, the window closes, and then the event for the key prints to stdout. Shouldn't this happen _before_ the window is closed? This is what I see in my REPL...kind of unintuitive (the Stopped AxGame line is printed inside of an :around close-window):

```
GAME> (init-game)
Started AxGame
#<GAME {10095F9093}>
Framerate: 16.760 ms/f, 59.67 fps
Framerate: 16.760 ms/f, 59.67 fps
Stopped AxGame
Key pressed: Escape
GAME>
```

**Comment by rpav** [comment]
1) You don't _eval_ in a package, you _read_ in a package, i.e., make sure `*PACKAGE*` is bound to what you want when you `READ`.  It does however appear that the dynamic environment is not preserved within `sdl2:in-main-thread`.  I'm not sure this can be implemented in such a way that it does.  However, you can bind it _within_ `sdl2:in-main-thread` and it should work:

``` lisp
(sdl2:in-main-thread ()
  (let ((*package* ...))
    (read ...)))
```

2) You're probably closing the window on `:keydown` and the one you see is on `:keyup`.

**Comment by mfiano** [comment]
1) okay, that makes sense.

2) that is not the case - I use "Key released: ..." for :keyup

**Comment by rpav** [comment]
Is this for tradewarz?  It looks like [your `key-down` method](https://github.com/axionix/tradewarz/blob/master/input-game.lisp#L3) is regular but [the one that prints the key](https://github.com/axionix/tradewarz/blob/master/input.lisp#L10) is `:after`.

**Comment by mfiano** [comment]
No, not tradewarz, but the issue was similar. You're right the printing method should be :around. Fixed.
